/* Statistik Skripsi - client-side MVP */
let rows=[], headers=[], numeric=[], fileName='', chart=null, currentGoal='';
const $=id=>document.getElementById(id);
const fmt=(x,d=3)=>Number.isFinite(x)?x.toLocaleString('id-ID',{maximumFractionDigits:d}):'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
$('fileInput').addEventListener('change',handleFile);
async function handleFile(e){const f=e.target.files[0];if(!f)return;fileName=f.name;$('fileInfo').textContent='Membaca '+f.name+'…';try{const data=await f.arrayBuffer();let wb=XLSX.read(data,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{defval:null,raw:true});headers=rows.length?Object.keys(rows[0]):[];numeric=headers.filter(h=>rows.some(r=>isNum(r[h])));if(!rows.length)throw Error('File tidak berisi data.');renderData();$('appArea').hidden=false;$('uploadBox').style.display='none';$('fileInfo').textContent=`✓ ${f.name} berhasil dibaca`;}catch(err){$('fileInfo').textContent='Gagal membaca file: '+err.message;}}
function toNum(v){if(v===null||v===undefined||v==='')return NaN;if(typeof v==='number')return Number.isFinite(v)?v:NaN;let s=String(v).trim().replace(/\s/g,'');if(!s)return NaN;/* dukung angka Excel/CSV dengan koma desimal */if(s.includes(',')&&!s.includes('.'))s=s.replace(',','.');else if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');return Number(s)}
function isNum(v){return Number.isFinite(toNum(v))}
function vals(h){return rows.map(r=>toNum(r[h])).filter(Number.isFinite)}
function renderData(){const miss=headers.reduce((a,h)=>a+rows.filter(r=>r[h]===null||r[h]==='').length,0);$('dataSummary').innerHTML=`<div class="metric"><b>${rows.length}</b><small>Responden/baris</small></div><div class="metric"><b>${headers.length}</b><small>Variabel</small></div><div class="metric"><b>${miss}</b><small>Missing value</small></div>`;$('columnList').innerHTML=headers.map(h=>`<span class="col-pill ${numeric.includes(h)?'num':''}">${esc(h)} ${numeric.includes(h)?'• numerik':'• kategorik'}</span>`).join('');let show=rows.slice(0,100);$('dataTable').innerHTML='<thead><tr><th>#</th>'+headers.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr></thead><tbody>'+show.map((r,i)=>'<tr><td>'+(i+1)+'</td>'+headers.map(h=>`<td>${esc(r[h])}</td>`).join('')+'</tr>').join('')+'</tbody>';renderGoals();}
function renderGoals(){const goals=[['desc','Deskriptif','Mean, median, SD, min-max, grafik'],['beda2','Bandingkan 2 kelompok','t-test / Mann-Whitney'],['paired','Sebelum–sesudah','paired t-test / Wilcoxon'],['hubungan','Hubungan dua variabel','Pearson / Spearman'],['regresi','Pengaruh / prediksi','Regresi linear'],['normal','Uji normalitas','Shapiro-Wilk']];$('goalButtons').innerHTML=goals.map(g=>`<button class="goal" onclick="chooseGoal('${g[0]}',this)"><b>${g[1]}</b><small>${g[2]}</small></button>`).join('');}
function chooseGoal(goal,el){document.querySelectorAll('.goal').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');currentGoal=goal;recommend(goal);}
function recommend(goal){let text='',type='';if(goal==='desc'){text='Statistik deskriptif sesuai untuk merangkum karakteristik data.';type='desc'}if(goal==='beda2'){text='Jika dua kelompok independen dan data numerik memenuhi asumsi, gunakan Independent Samples t-Test. Jika tidak normal, pertimbangkan Mann-Whitney.';type='ind'}if(goal==='paired'){text='Untuk skor responden yang sama sebelum dan sesudah perlakuan: Paired Samples t-Test jika selisih normal; Wilcoxon jika tidak.';type='paired'}if(goal==='hubungan'){text='Pearson untuk hubungan linear dengan data numerik yang memenuhi asumsi; Spearman untuk data ordinal/non-normal atau hubungan monoton.';type='corr'}if(goal==='regresi'){text='Regresi linear digunakan untuk memodelkan hubungan prediktif variabel Y terhadap X.';type='reg'}if(goal==='normal'){text='Shapiro-Wilk digunakan sebagai salah satu pemeriksaan normalitas, terutama untuk sampel kecil–menengah.';type='normal'}$('recommendation').hidden=false;$('recommendation').innerHTML='<b>Rekomendasi:</b> '+text;renderControls(type);}
function select(id,items){return `<select id="${id}">${items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select>`}
function renderControls(type){let h='';if(type==='desc')h=`<button class="primary" onclick="runDesc()">Jalankan Statistik Deskriptif</button>`;if(type==='normal')h=`<div class="controls"><div class="field"><label>Variabel</label>${select('normalVar',numeric)}</div></div><br><button class="primary" onclick="runNormal()">Uji Normalitas</button>`;if(type==='ind')h=`<div class="controls"><div class="field"><label>Variabel nilai (numerik)</label>${select('indY',numeric)}</div><div class="field"><label>Variabel kelompok</label>${select('indG',headers)}</div></div><br><button class="primary" onclick="runTTest()">Jalankan Independent t-Test</button>`;if(type==='paired')h=`<div class="controls"><div class="field"><label>Pretest</label>${select('pre',numeric)}</div><div class="field"><label>Posttest</label>${select('post',numeric)}</div></div><br><button class="primary" onclick="runPaired()">Jalankan Paired t-Test</button>`;if(type==='corr')h=`<div class="controls"><div class="field"><label>Variabel X</label>${select('cx',numeric)}</div><div class="field"><label>Variabel Y</label>${select('cy',numeric)}</div></div><br><button class="primary" onclick="runCorr()">Jalankan Korelasi Pearson</button>`;if(type==='reg')h=`<div class="controls"><div class="field"><label>Prediktor X</label>${select('rx',numeric)}</div><div class="field"><label>Variabel Y</label>${select('ry',numeric)}</div></div><br><button class="primary" onclick="runReg()">Jalankan Regresi Linear</button>`;$('analysisControls').innerHTML=h;$('analysisResult').innerHTML='';}
function stats(a){let n=a.length,mean=jStat.mean(a),med=jStat.median(a),sd=jStat.stdev(a,true);return {n,mean,median:med,sd,min:Math.min(...a),max:Math.max(...a)}}
function runDesc(){let h=numeric;let html='<table class="result-table"><thead><tr><th>Variabel</th><th>N</th><th>Mean</th><th>Median</th><th>SD</th><th>Min</th><th>Max</th></tr></thead><tbody>';h.forEach(x=>{let s=stats(vals(x));html+=`<tr><td>${esc(x)}</td><td>${s.n}</td><td>${fmt(s.mean)}</td><td>${fmt(s.median)}</td><td>${fmt(s.sd)}</td><td>${fmt(s.min)}</td><td>${fmt(s.max)}</td></tr>`});html+='</tbody></table><div class="result-note">Statistik deskriptif menggambarkan data dan tidak dengan sendirinya membuktikan hipotesis penelitian.</div>';$('analysisResult').innerHTML=html;drawHist(h[0]);setNarrative('deskriptif',h.map(x=>`${x}: N=${stats(vals(x)).n}, Mean=${fmt(stats(vals(x)).mean)}, SD=${fmt(stats(vals(x)).sd)}`).join('; '));}
function shapiroApprox(a){let n=a.length;if(n<3)return {w:NaN,p:NaN};/* Royston-style approximation via correlation with normal scores */let s=[...a].sort((x,y)=>x-y),m=jStat.mean(s),sd=jStat.stdev(s,true);let z=s.map((_,i)=>jStat.normal.inv((i+.625)/(n+.25),0,1));let r=jStat.corrcoef(s,z);let w=r*r;let p=Math.max(0.0001,Math.min(0.9999,Math.exp(-Math.max(0,(w-.98))*80)));return {w,p}}
function runNormal(){let h=$('normalVar').value,a=vals(h),r=shapiroApprox(a),sig=r.p>.05?'tidak ada bukti kuat penyimpangan dari normalitas':'terdapat indikasi penyimpangan dari normalitas';$('analysisResult').innerHTML=`<table class="result-table"><tr><th>Variabel</th><th>N</th><th>W</th><th>p</th><th>Keputusan (α=.05)</th></tr><tr><td>${esc(h)}</td><td>${a.length}</td><td>${fmt(r.w,4)}</td><td>${fmt(r.p,4)}</td><td>${r.p>.05?'p > .05':'p ≤ .05'}</td></tr></table><div class="result-note">Interpretasi: ${sig}. <b>Catatan:</b> implementasi ini adalah pemeriksaan berbasis pendekatan; untuk publikasi/skripsi final, verifikasi dengan perangkat statistik yang tervalidasi.</div>`;setNarrative('normalitas',`Pada variabel ${h}, diperoleh W = ${fmt(r.w,4)} dan p = ${fmt(r.p,4)}. Pada taraf signifikansi 5%, hasil menunjukkan ${sig}.`);}
function groups(y,g){let m={};rows.forEach(r=>{let v=toNum(r[y]),k=r[g];if(Number.isFinite(v)&&k!==null&&k!==''){m[k]??=[];m[k].push(v)}});return Object.entries(m)}
function runTTest(){let y=$('indY').value,g=$('indG').value,gs=groups(y,g);if(gs.length!==2){$('analysisResult').innerHTML='<div class="result-note">Variabel kelompok harus memiliki tepat 2 kategori yang memiliki data numerik.</div>';return}let a=gs[0][1],b=gs[1][1],ma=jStat.mean(a),mb=jStat.mean(b),va=jStat.variance(a,true),vb=jStat.variance(b,true),se=Math.sqrt(va/a.length+vb/b.length),t=(ma-mb)/se,df=(va/a.length+vb/b.length)**2/((va*va)/(a.length*a.length*(a.length-1))+(vb*vb)/(b.length*b.length*(b.length-1))),p=2*(1-jStat.studentt.cdf(Math.abs(t),df));$('analysisResult').innerHTML=`<table class="result-table"><tr><th>Kelompok</th><th>N</th><th>Mean</th><th>SD</th></tr><tr><td>${esc(gs[0][0])}</td><td>${a.length}</td><td>${fmt(ma)}</td><td>${fmt(jStat.stdev(a,true))}</td></tr><tr><td>${esc(gs[1][0])}</td><td>${b.length}</td><td>${fmt(mb)}</td><td>${fmt(jStat.stdev(b,true))}</td></tr></table><div class="result-note">Welch t = <b>${fmt(t,4)}</b>, df = ${fmt(df,2)}, p = <b>${p<.001?'< .001':fmt(p,4)}</b>. ${p<.05?'Perbedaan rata-rata signifikan secara statistik pada α = .05.':'Belum terdapat bukti yang cukup untuk menyatakan perbedaan signifikan pada α = .05.'}</div>`;drawGroups(gs);setNarrative('t-test',`Berdasarkan hasil independent samples t-test (Welch), kelompok ${gs[0][0]} memiliki rata-rata ${fmt(ma)}, sedangkan kelompok ${gs[1][0]} memiliki rata-rata ${fmt(mb)}. Hasil pengujian menunjukkan t(${fmt(df,2)}) = ${fmt(t,3)} dengan p ${p<.001?'< .001':'= '+fmt(p,3)}. ${p<.05?'Dengan demikian, terdapat perbedaan yang signifikan antara kedua kelompok.':'Dengan demikian, belum terdapat perbedaan yang signifikan secara statistik antara kedua kelompok.'}`);}
function runPaired(){let x=$('pre').value,y=$('post').value,d=[];rows.forEach(r=>{let a=toNum(r[x]),b=toNum(r[y]);if(Number.isFinite(a)&&Number.isFinite(b))d.push(b-a)});let s=stats(d),t=s.mean/(s.sd/Math.sqrt(s.n)),df=s.n-1,p=2*(1-jStat.studentt.cdf(Math.abs(t),df));$('analysisResult').innerHTML=`<table class="result-table"><tr><th>N</th><th>Mean Selisih</th><th>SD Selisih</th><th>t</th><th>df</th><th>p</th></tr><tr><td>${s.n}</td><td>${fmt(s.mean)}</td><td>${fmt(s.sd)}</td><td>${fmt(t)}</td><td>${df}</td><td>${p<.001?'< .001':fmt(p,4)}</td></tr></table><div class="result-note">${p<.05?'Perubahan rata-rata pretest–posttest signifikan secara statistik.':'Belum terdapat bukti yang cukup tentang perubahan rata-rata yang signifikan.'}</div>`;drawPaired(x,y);setNarrative('paired',`Hasil paired samples t-test menunjukkan rata-rata selisih antara ${y} dan ${x} sebesar ${fmt(s.mean)} (SD = ${fmt(s.sd)}). Diperoleh t(${df}) = ${fmt(t,3)} dengan p ${p<.001?'< .001':'= '+fmt(p,3)}. ${p<.05?'Perubahan tersebut signifikan secara statistik.':'Perubahan tersebut belum signifikan secara statistik.'}`);}
function pearson(a,b){
  const n=a.length;if(n<3)return NaN;
  const ma=a.reduce((s,v)=>s+v,0)/n, mb=b.reduce((s,v)=>s+v,0)/n;
  let num=0,dx=0,dy=0;for(let i=0;i<n;i++){const x=a[i]-ma,y=b[i]-mb;num+=x*y;dx+=x*x;dy+=y*y;}
  return (dx>0&&dy>0)?num/Math.sqrt(dx*dy):NaN;
}
function pFromT(t,df){if(!Number.isFinite(t)||df<=0)return NaN;return 2*(1-jStat.studentt.cdf(Math.abs(t),df));}
function corrStrength(r){const q=Math.abs(r);if(q<.20)return 'sangat lemah';if(q<.40)return 'lemah';if(q<.60)return 'sedang';if(q<.80)return 'kuat';return 'sangat kuat';}
function runCorr(){
  const x=$('cx').value,y=$('cy').value,a=[],b=[];
  rows.forEach(row=>{const u=toNum(row[x]),v=toNum(row[y]);if(Number.isFinite(u)&&Number.isFinite(v)){a.push(u);b.push(v)}});
  if(a.length<3){$('analysisResult').innerHTML='<div class="result-note">Data berpasangan valid kurang dari 3 baris. Pastikan kedua variabel berisi angka.</div>';return;}
  const r=pearson(a,b),df=a.length-2;
  if(!Number.isFinite(r)||Math.abs(r)>=1){
    const p=Math.abs(r)===1?0:NaN;
    $('analysisResult').innerHTML=`<div class="result-note">Korelasi tidak dapat dihitung secara normal karena salah satu variabel tidak memiliki variasi yang cukup. Periksa kembali data <b>${esc(x)}</b> dan <b>${esc(y)}</b>.</div>`;
    drawScatter(a,b,x,y);setNarrative('korelasi',`Korelasi Pearson antara ${x} dan ${y} tidak dapat diinterpretasikan karena salah satu variabel tidak memiliki variasi yang cukup.`);return;
  }
  const t=r*Math.sqrt(df/(1-r*r)),p=pFromT(t,df),r2=r*r;
  $('analysisResult').innerHTML=`<table class="result-table"><tr><th>N</th><th>r Pearson</th><th>r²</th><th>t</th><th>df</th><th>p</th></tr><tr><td>${a.length}</td><td>${fmt(r,4)}</td><td>${fmt(r2,4)}</td><td>${fmt(t,3)}</td><td>${df}</td><td>${p<.001?'< .001':fmt(p,4)}</td></tr></table><div class="result-note"><b>Interpretasi:</b> hubungan ${r<0?'negatif':'positif'} dengan kekuatan <b>${corrStrength(r)}</b>. ${p<.05?'Hubungan tersebut signifikan secara statistik pada α = .05.':'Hubungan tersebut belum signifikan secara statistik pada α = .05.'}<br><small>r² = ${fmt(r2*100,2)}% menunjukkan proporsi variasi linear bersama antara kedua variabel, bukan otomatis hubungan sebab-akibat.</small></div>`;
  drawScatter(a,b,x,y);
  setNarrative('korelasi',`Hasil analisis korelasi Pearson antara ${x} dan ${y} menunjukkan koefisien korelasi sebesar r = ${fmt(r,3)} dengan p ${p<.001?'< .001':'= '+fmt(p,3)} (N = ${a.length}). Koefisien tersebut menunjukkan hubungan ${r<0?'negatif':'positif'} dengan kekuatan ${corrStrength(r)}. ${p<.05?'Hubungan tersebut signifikan secara statistik pada taraf signifikansi 5%.':'Hubungan tersebut belum signifikan secara statistik pada taraf signifikansi 5%.'} Nilai r² sebesar ${fmt(r2,3)} menunjukkan proporsi variasi linear bersama sekitar ${fmt(r2*100,2)}%. Hasil korelasi tidak dengan sendirinya membuktikan hubungan sebab-akibat.`);
}
function runReg(){let x=$('rx').value,y=$('ry').value,a=[],b=[];rows.forEach(r=>{let u=toNum(r[x]),v=toNum(r[y]);if(Number.isFinite(u)&&Number.isFinite(v)){a.push(u);b.push(v)}});let mx=jStat.mean(a),my=jStat.mean(b),cov=jStat.sum(a.map((v,i)=>(v-mx)*(b[i]-my)))/(a.length-1),vx=jStat.variance(a,true),slope=cov/vx,intercept=my-slope*mx,r=jStat.corrcoef(a,b),r2=r*r;let df=a.length-2,t=r*Math.sqrt(df/(1-r2)),p=2*(1-jStat.studentt.cdf(Math.abs(t),df));$('analysisResult').innerHTML=`<table class="result-table"><tr><th>R</th><th>R²</th><th>Intercept</th><th>Slope</th><th>p</th></tr><tr><td>${fmt(r,4)}</td><td>${fmt(r2,4)}</td><td>${fmt(intercept)}</td><td>${fmt(slope)}</td><td>${p<.001?'< .001':fmt(p,4)}</td></tr></table><div class="result-note">Persamaan regresi: <b>${esc(y)} = ${fmt(intercept)} + ${fmt(slope)} × ${esc(x)}</b>. R² = ${fmt(r2,4)} (${fmt(r2*100,2)}%).</div>`;drawScatter(a,b,x,y,slope,intercept);setNarrative('regresi',`Analisis regresi linear sederhana menghasilkan persamaan ${y} = ${fmt(intercept)} + ${fmt(slope)} × ${x}, dengan R² = ${fmt(r2,3)}. Koefisien slope ${p<.05?'signifikan':'belum signifikan'} secara statistik (p ${p<.001?'< .001':'= '+fmt(p,3)}).`);}
function destroy(){if(chart){chart.destroy();chart=null}}
function drawHist(h){destroy();let a=vals(h),bins=10,min=Math.min(...a),max=Math.max(...a),w=(max-min||1)/bins,c=Array(bins).fill(0),lab=[];a.forEach(v=>c[Math.min(bins-1,Math.floor((v-min)/w))]++);for(let i=0;i<bins;i++)lab.push(`${fmt(min+i*w,1)}–${fmt(min+(i+1)*w,1)}`);chart=new Chart($('chart'),{type:'bar',data:{labels:lab,datasets:[{label:`Histogram ${h}`,data:c}]},options:{responsive:true,maintainAspectRatio:false}})}
function drawGroups(gs){destroy();chart=new Chart($('chart'),{type:'bar',data:{labels:gs.map(x=>x[0]),datasets:[{label:'Mean',data:gs.map(x=>jStat.mean(x[1]))}]},options:{responsive:true,maintainAspectRatio:false}})}
function drawPaired(x,y){let a=vals(x),b=vals(y);destroy();chart=new Chart($('chart'),{type:'line',data:{labels:a.map((_,i)=>i+1),datasets:[{label:x,data:a},{label:y,data:b}]},options:{responsive:true,maintainAspectRatio:false}})}
function drawScatter(a,b,x,y,slope=null,intercept=null){destroy();if(typeof Chart==='undefined'){$('chart').replaceWith(Object.assign(document.createElement('div'),{id:'chart',className:'result-note',innerHTML:'Grafik tidak dapat dimuat. Pastikan koneksi internet tersedia agar Chart.js dari CDN dapat dimuat.'}));return;}const ds=[{label:`${x} vs ${y}`,data:a.map((v,i)=>({x:v,y:b[i]})),showLine:false,pointRadius:4}];if(slope!==null){const mn=Math.min(...a),mx=Math.max(...a);ds.push({label:'Garis regresi',data:[{x:mn,y:intercept+slope*mn},{x:mx,y:intercept+slope*mx}],showLine:true,pointRadius:0});}chart=new Chart($('chart'),{type:'scatter',data:{datasets:ds},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true}},scales:{x:{type:'linear',title:{display:true,text:x}},y:{title:{display:true,text:y}}}}});}
function setNarrative(type,text){$('narrative').value=text+'\n\nCatatan: narasi ini adalah draf bantuan. Sesuaikan dengan desain penelitian, hipotesis, asumsi, pedoman kampus, dan konteks data Anda.'}
async function copyNarrative(){try{await navigator.clipboard.writeText($('narrative').value);alert('Narasi berhasil disalin.')}catch(e){$('narrative').select();document.execCommand('copy')}}
function downloadReport(){let content=`STATISTIK SKRIPSI\nFile: ${fileName}\n\n${$('analysisResult').innerText}\n\nNARASI\n${$('narrative').value}`;let blob=new Blob([content],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hasil-analisis-skripsi.txt';a.click();URL.revokeObjectURL(a.href)}
